import type { Metadata } from "next";
import { Geist, Geist_Mono, Geologica } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import SkipLink from "./components/SkipLink";
import Nav from "./components/Nav";
import ScrollReset from "./components/ScrollResetClient";
import ParallaxScroll from "./components/ParallaxScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const brandelLuchador = localFont({
  src: "../public/brandel-luchador.regular.ttf",
  variable: "--font-brandel-luchador",
  display: "swap",
});

const itKroxenDemo = localFont({
  src: "../public/brandel-luchador.regular.ttf",
  variable: "--font-it-kroxen-demo",
  display: "swap",
});

const jaldi = localFont({
    src: "../public/Jaldi-Regular.ttf",
    variable: "--font-jaldi",
    display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   return (
     <html
       lang="en"
       className={`${geistSans.variable} ${geistMono.variable} ${geologica.variable} ${brandelLuchador.variable} ${itKroxenDemo.variable} ${jaldi.variable} h-full antialiased`}
     >
       <head>
         <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
       </head>
       <body className="min-h-full flex flex-col" suppressHydrationWarning>
          <ScrollReset />
          <ParallaxScroll />
         <SkipLink />
         <Nav />
         {children}
       </body>
     </html>
   );
}
